version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build -t karma_webapp .

     # deploy the image
     # - run: docker push company/app:$CIRCLE_BRANCH