version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login --username=liam@tengelisconsulting.com --password=${HEROKU_API_KEY} registry.heroku.com
     - run: docker build -t registry.heroku.com/karma-webapp-canary/web .
     - run: docker push registry.heroku.com/karma-webapp-canary/web
     - run: pwd && ls
